manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: marlboro-red                            
      url-base: https://github.com/marlboro-red    
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: prospector-zmk-module                 # <--- and these
      remote: marlboro-red                          # <---
      revision: main       
  self:
    path: config
